# REMEMBER TO EDIT THIS BEFORE DEPLOYING!!!

# the path to your blog's icon (looking default into blog/source folder):
favicon: https://ritie-jonie-1312559530.cos.ap-nanjing.myqcloud.com/favicon/stitch_sleepy.png

# the path to manifest.json
manifest: /manifest.json

# show excerpt on post list
show_excerpt: false

# light/dark/auto color scheme
color_scheme: auto

# show floating color theme toggle
show_color_scheme_toggle: true

# uppercase categories
uppercase_categories: true

# capitalize tag names on tags page
capitalize_tags: false

# add hashtag prefix before tags
hashtag_prefix_before_tags: true

# rainbow!
rainbow_banner: true
rainbow_banner_colors:
  - '#e50000'
  - '#ff8d00'
  - '#ffee00'
  - '#008121'
  - '#004cff'
  - '#760188'
# choose from [auto, always]
rainbow_banner_shown: always
# Pride Month by default
rainbow_banner_month: 6

# navigation config
nav:
  # the title displays in the upper left corner which won't change
  title: BLOGS
  # the items displays in the upper right corner
  items:
    # these items will display as a link
    Archives: /archives
    Friends: /friends
    About: /about
    Version: /version
    Comments: /comments
    # these will be automatically be an icon
    GitHub: https://github.com/jonie-ritie
    Discord: https://discord.gg/HsKMJdRc
    QQ: https://jq.qq.com/?_wv=1027&k=2fatNYU9
    Miniprogram:
    Email: 'mailto:2465373218@qq.com'

## footer items
#footer:
#  # the title
#  Blog:
#    # the items after the title, display as links
#    Blog: /
#    Archives: /archives
#    Friends: /friends
#    About: /about
#    RSS: /atom.xml
#  # also the title
#  Projects:
#    # the items
#    # RSA CLI: https://github.com/MrWillCom/rsa-cli
#    LOVE HEALS ALL:
#  # the title
#  Me:
#    # items
#    GitHub: https://github.com/jonie-ritie
#    Email: 'mailto:2465373218@qq.com'
#    Discord: https://discord.gg/HsKMJdRc
#    QQ: https://jq.qq.com/?_wv=1027&k=2fatNYU9

# the license your posts under
license: CC BY-NC 4.0
# the link of your license
license_link: https://creativecommons.org/licenses/by-nc/4.0

# REMEMBER TO EDIT THIS BEFORE DEPLOYING!!!